sonar.projectKey=BookStoreApp
sonar.projectName=BookStoreApp
sonar.projectVersion=1.0

sonar.sources=BookStoreApp
sonar.tests=BookStoreApp.Tests

sonar.cs.opencover.reportsPaths=BookStoreApp.Tests/TestResults/**/*.xml

sonar.host.url=http://localhost:9000
sonar.login=sqp_f0e11169ff7052592628c0a051bb1bb2f6b584eb
